---
- name: Timezone 
  hosts: localhost
  become: yes
  tasks:
    - name: Update the Ubuntu Repository
      apt: update_cache=yes
      ignore_errors: yes

    - name: Set Timezone
      timezone:
        name: Asia/Kolkata
...
